name: message_map
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^3.0.4
  cloud_firestore: ^2.5.4
  cupertino_icons: ^1.0.2
  firebase_core: ^1.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  mapbox_gl: ^0.13.0

dev_dependencies:
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
