name: geo_tagging
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^3.0.4
  cloud_firestore: ^2.5.4
  equatable: ^2.0.3
  firebase_core: ^1.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  google_fonts: ^2.1.0
  json_annotation: ^4.3.0
  location: ^4.3.0
  mapbox_gl: ^0.13.0
  provider: ^6.0.1
  responsive_builder: ^0.4.1

dev_dependencies:
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
