name: Deploy to Firebase Hosting on main

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Flutter Action
        uses: subosito/flutter-action@v1.5.1
        with:
          channel: master

      - name: Flutter Build Web
        run: flutter build web --web-renderer html

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MESSAGE_MAP_B46D3 }}"
          channelId: live
          projectId: message-map-b46d3
